<a href="https://colab.research.google.com/github/jamg-upv/CAHOS19/blob/main/python/visualizacion_evolucion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Empezamos importando el csv orignial**#
llamado "Capacidad_Asistencial_Historico_gobes.csv", convirtiendo las columnas que tocan en fechas

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from datetime import datetime, timedelta

direccion0="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/inputtables/Capacidad_Asistencial_Historico_gobes.csv"
capacidad_asistencial=pd.read_csv(direccion0, delimiter=';', encoding='latin_1')
capacidad_asistencial['Fecha'] = pd.to_datetime(capacidad_asistencial['Fecha'], format="%d/%m/%Y")

byprovincia=capacidad_asistencial.groupby(['Provincia'], as_index=False).agg('mean')
byprovincia

                 Provincia  COD_CCAA  ...  OCUPADAS_COVID19  OCUPADAS_NO_COVID19
0                 Albacete       8.0  ...         31.032828           180.160354
1         Alicante/Alacant      10.0  ...        165.023990           755.881313
2                  Almería       1.0  ...         47.036616           221.732323
3              Araba/Álava      16.0  ...         29.772727           147.316919
4                 Asturias       3.0  ...        125.063131           626.803030
5                  Badajoz      11.0  ...         44.683081           323.666667
6           Balears, Illes       4.0  ...         84.986111           646.337121
7                Barcelona       9.0  ...        681.268939          4383.993687
8                  Bizkaia      16.0  ...        108.064394           535.775253
9                   Burgos       7.0  ...         45.118687           182.654040
10               Cantabria       6.0  ...         36.565657           301.083333
11      Castellón/Castelló      10.0  ...         40.292929           242.780303
12                   Ceuta      18.0  ...          6.935361            21.195184
13             Ciudad Real       8.0  ...         47.804293           247.209596
14               Coruña, A      12.0  ...         69.449495           709.590909
15                  Cuenca       8.0  ...         12.007576            53.239899
16                 Cáceres      11.0  ...         25.949495           179.515152
17                   Cádiz       1.0  ...         88.332071           481.878788
18                 Córdoba       1.0  ...         58.642677           288.481061
19                Gipuzkoa      16.0  ...         60.708333           325.838384
20                  Girona       9.0  ...         71.830808           471.554293
21                 Granada       1.0  ...        112.152778           341.592172
22             Guadalajara       8.0  ...         26.354798            69.089646
23                  Huelva       1.0  ...         26.589646           157.207071
24                  Huesca       2.0  ...         21.111111           103.833333
25                    Jaén       1.0  ...         57.922980           181.880051
26                    León       7.0  ...         55.832071           272.049242
27                  Lleida       9.0  ...         40.551768           235.058081
28                    Lugo      12.0  ...         10.207071           187.881313
29                  Madrid      13.0  ...        917.608586          3489.035354
30                 Melilla      19.0  ...          8.092172            21.054293
31                  Murcia      14.0  ...        113.006313           716.262626
32                  Málaga       1.0  ...        103.609848           626.056818
33                 Navarra      15.0  ...         51.493687           353.030303
34                 Ourense      12.0  ...         21.282828           228.940657
35                Palencia       7.0  ...         25.267949            75.161538
36             Palmas, Las       5.0  ...         45.013889           595.737374
37              Pontevedra      12.0  ...         40.080808           493.146465
38               Rioja, La      17.0  ...         33.766414           147.608586
39               Salamanca       7.0  ...         38.284091           167.325758
40  Santa Cruz de Tenerife       5.0  ...         42.542929           598.054293
41                 Segovia       7.0  ...         13.487374            58.395202
42                 Sevilla       1.0  ...        119.954545           745.053030
43                   Soria       7.0  ...         13.256313            49.660354
44               Tarragona       9.0  ...         74.555556           590.873737
45                  Teruel       2.0  ...         17.969697            61.099747
46                  Toledo       8.0  ...         97.279040           277.501263
47       Valencia/València      10.0  ...        235.797980          1053.684343
48              Valladolid       7.0  ...         78.655303           255.690657
49                  Zamora       7.0  ...         22.112374            78.559343
50                Zaragoza       2.0  ...        128.152778           583.770202
51                   Ávila       7.0  ...         16.739899            68.906566

[52 rows x 6 columns]

In [2]:
#ordena el archivo primero por fechas y luego por código provincial(cap_Asis) Y ccaa(cap_asis00)
cap_asis = capacidad_asistencial.sort_values(['Fecha', 'Cod_Provincia'])
cap_asis00=capacidad_asistencial.sort_values(['Fecha', 'CCAA'])

In [3]:
#Lo que hacemos es agrupar según provincia (cap_asis1) y por CCAA (cap_asis01), y luego por fecha para que haga la suma de las de: TOTAL_CAMAS, OCUPADAS_COVID19, OCUPADAS_NO_COVID19
cap_asis1=cap_asis.groupby(['Cod_Provincia', 'Fecha'])['TOTAL_CAMAS', 'OCUPADAS_COVID19', 'OCUPADAS_NO_COVID19'].apply(sum)
cap_asis01=cap_asis00.groupby(['CCAA', 'Fecha'])['TOTAL_CAMAS', 'OCUPADAS_COVID19', 'OCUPADAS_NO_COVID19'].apply(sum)

cap_asis01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

                       TOTAL_CAMAS  OCUPADAS_COVID19  OCUPADAS_NO_COVID19
CCAA       Fecha
ANDALUCÍA  2020-08-19        16209               343                 8535
           2020-08-20        16369               340                 8992
           2020-08-21        16360               369                 8248
           2020-08-22        16363               361                 8300
           2020-08-23        16612               387                 8753
...                            ...               ...                  ...
PAÍS VASCO 2021-05-05         5018               710                 3172
           2021-05-06         5015               686                 3115
           2021-05-07         4947               636                 2999
           2021-05-08         4947               638                 2986
           2021-05-09         4945               670                 3127

[5015 rows x 3 columns]

In [4]:
#Ahora lo que buscamos es dejar solo la comulma de OCUPADAS_COVID19 en funcion de la provincia y las fechas
cap_asis2=cap_asis1.drop(['TOTAL_CAMAS', 'OCUPADAS_NO_COVID19'], axis=1)
cap_asis02=cap_asis01.drop(['TOTAL_CAMAS', 'OCUPADAS_NO_COVID19'], axis=1)
cap_asis02

                       OCUPADAS_COVID19
CCAA       Fecha
ANDALUCÍA  2020-08-19               343
           2020-08-20               340
           2020-08-21               369
           2020-08-22               361
           2020-08-23               387
...                                 ...
PAÍS VASCO 2021-05-05               710
           2021-05-06               686
           2021-05-07               636
           2021-05-08               638
           2021-05-09               670

[5015 rows x 1 columns]

In [5]:
#Generamos un archivo CSV con la nueva tabla creada con los nuevos agrupamientos

cap_asis2.to_csv('provincias_camas_totuci_covid_nocovid.csv')
cap_asis02.to_csv('CCAA_camas_totuci_covid_nocovid.csv')

#**Importamos nuevo csv reorganizado y estructurado (Cod_Provincia y CCAA)**#
llamado: "provincias_camas_totuci_covid_nocovid.csv" por código y "CCAA_camas_totuci_covid_nocovid.csv" por CCAA de los outputtable

Aquí lo que haremos será la puesta a punto para meterlo directamente en el flourish (transpondremos filas y columnas)

In [6]:
direccion1="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/outputtables/provincias_camas_totuci_covid_nocovid.csv"
direccion01="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/outputtables/CCAA_camas_totuci_covid_nocovid.csv"
provincias_camas=pd.read_csv(direccion1, delimiter=',', encoding='latin_1')
CCAA_camas_COVID=pd.read_csv(direccion01, delimiter=',')
CCAA_camas_COVID

            CCAA       Fecha  OCUPADAS_COVID19
0      ANDALUCÍA  2020-08-19               343
1      ANDALUCÍA  2020-08-20               340
2      ANDALUCÍA  2020-08-21               369
3      ANDALUCÍA  2020-08-22               361
4      ANDALUCÍA  2020-08-23               387
...          ...         ...               ...
5010  PAÍS VASCO  2021-05-05               710
5011  PAÍS VASCO  2021-05-06               686
5012  PAÍS VASCO  2021-05-07               636
5013  PAÍS VASCO  2021-05-08               638
5014  PAÍS VASCO  2021-05-09               670

[5015 rows x 3 columns]

In [7]:
#Intento trasponer las columnas de fecha y 'OCUPADAS_COVID' por columnas para poder hacer el gráfico

provincias_camas1=provincias_camas.pivot(index='Cod_Provincia', columns='Fecha', values='OCUPADAS_COVID19')
CCAA_camas_COVID1=CCAA_camas_COVID.pivot(index='CCAA', columns='Fecha', values='OCUPADAS_COVID19')
CCAA_camas_COVID1

Fecha                 2020-08-19  2020-08-20  ...  2021-05-08  2021-05-09
CCAA                                          ...
ANDALUCÍA                  343.0       340.0  ...      1183.0      1252.0
ARAGÓN                     536.0       541.0  ...       358.0       383.0
ASTURIAS                    22.0        21.0  ...       167.0       169.0
CANTABRIA                   31.0        35.0  ...       104.0       116.0
CASTILLA LA MANCHA         122.0       130.0  ...       407.0       422.0
CASTILLA Y LEÓN            207.0       210.0  ...       421.0       448.0
CATALUÑA                   980.0       995.0  ...      1591.0      1611.0
CEUTA                        0.0         0.0  ...        21.0        19.0
COMUNIDAD VALENCIANA       351.0       339.0  ...       155.0       166.0
EXTREMADURA                 44.0        37.0  ...        51.0        59.0
GALICIA                     86.0        87.0  ...       186.0       205.0
ISLAS BALEARES             196.0       194.0  ...        57.0        63.0
ISLAS CANARIAS             106.0       105.0  ...       208.0       218.0
LA RIOJA                    13.0        18.0  ...        68.0        73.0
MADRID                    1293.0      1361.0  ...      2302.0      2432.0
MELILLA                      6.0         7.0  ...        16.0        20.0
MURCIA                     118.0       108.0  ...        65.0        72.0
NAVARRA                     52.0        56.0  ...       135.0       133.0
PAÍS VASCO                 333.0       342.0  ...       638.0       670.0

[19 rows x 264 columns]

In [8]:
#Exportamos la nueva tabla para representar en el florish
provincias_camas1.to_csv('provincias_camas_covid.csv')
CCAA_camas_COVID1.to_csv('CCAA_camas_COVID1.csv')

#**Realizamos archivo para tener camas con covid/camas totales**#

In [ ]:
cap_asis3=cap_asis01.drop(['OCUPADAS_NO_COVID19'], axis=1) #Eliminamos la que no nos va a ser útil en esta
PORCENTAJE_COVID=(cap_asis3['OCUPADAS_COVID19']/cap_asis3['TOTAL_CAMAS'])*100 #Calculamos los % de camas con covid sobre el total
cap_asis3['PORCENTAJE_COVID']=PORCENTAJE_COVID #Lo metemos en una columna del Data Frame
cap_asis31=cap_asis3.drop(['OCUPADAS_COVID19', 'TOTAL_CAMAS'], axis=1)#Eliminamos el resto de columnas dejando solo la del %
cap_asis31=cap_asis31.round({'PORCENTAJE_COVID':2}) #Hacemos que el % solo tenga dos decimales

cap_asis31

In [12]:
#Exportamos a un csv nuevo para poder trasponer las columnas y poder hacer la bar race
cap_asis31.to_csv('porcentaje_covid_CCAA.csv')
#Importamos nuevamente el csv
direccion3="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/outputtables/porcentaje_covid_CCAA.csv"
porcentaje_covid_CCAA=pd.read_csv(direccion3, delimiter=',')
#Trasponemos las columnas a filas
porcentaje_camascovid_CCAA=porcentaje_covid_CCAA.pivot(index='CCAA', columns='Fecha', values='PORCENTAJE_COVID')
#Exportamos csv final para la bar race
porcentaje_camascovid_CCAA.to_csv('porcentaje_camascovid_CCAA.csv')

#**Realizamos archivo para tener camas ocupadas/camas totales**#

In [16]:
cap_asis4=cap_asis01
CAMAS_TOTALES_OCUPADAS=(cap_asis4['OCUPADAS_COVID19']+cap_asis4['OCUPADAS_NO_COVID19'])
cap_asis4['CAMAS_TOTALES_OCUPADAS']=CAMAS_TOTALES_OCUPADAS
PORCENTAJE_CAMAS_TOTALES_OCUPADAS=(cap_asis4['CAMAS_TOTALES_OCUPADAS']/cap_asis4['TOTAL_CAMAS'])*100
cap_asis4['PORCENTAJE_CAMAS_TOTALES_OCUPADAS']=PORCENTAJE_CAMAS_TOTALES_OCUPADAS
cap_asis4=cap_asis4.round({'PORCENTAJE_CAMAS_TOTALES_OCUPADAS':2})
cap_asis41=cap_asis4.drop(['TOTAL_CAMAS', 'OCUPADAS_COVID19','OCUPADAS_NO_COVID19', 'CAMAS_TOTALES_OCUPADAS'], axis=1)

cap_asis41.to_csv('porcentaje_camas_totales_ocupadas.csv')

In [19]:

direccion4="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/outputtables/porcentaje_camas_totales_ocupadas.csv"
porcentaje_camas_totales_ocupadas=pd.read_csv(direccion4, ',')
porcentaje_camas_totales_ocupadas_barrace=porcentaje_camas_totales_ocupadas.pivot(index='CCAA',columns='Fecha', values='PORCENTAJE_CAMAS_TOTALES_OCUPADAS')
porcentaje_camas_totales_ocupadas_barrace
porcentaje_camas_totales_ocupadas_barrace.to_csv('porcentaje_camas_totales_ocupadas_barrace.csv')

#**IMPORTAMOS LOS DATOS DE LA POBLACIÓN ESPAÑOLA POR CCAA**#
Por CCAA, por provincia, por rango de edad (0-4, 5-9, 10-14, 15-19,...)

In [ ]:
direccion2="https://raw.githubusercontent.com/jamg-upv/CAHOS19/main/inputtables/0ccaa003.csv"
poblacion_ccaa_provincias=pd.read_csv(direccion2, delimiter=';')
poblacion_ccaa_provincias.head

In [ ]:
#Vemos los nombres por los que trata las distintas CCAA
cp=poblacion_ccaa_provincias['Comunidades y provincias'].unique()
#'ANDALUCÍA', 'ARAGÓN', 'ASTURIAS, PRINCIPADO DE' 'BALEARS, ILLES', 'CANARIAS', 'CANTABRIA', 'CASTILLA Y LEÓN',
#'CASTILLA - LA MANCHA', 'CATALUÑA', 'COMUNITAT VALENCIANA', 'EXTREMADURA', 'GALICIA', 'MADRID, COMUNIDAD DE', 'MURCIA, REGIÓN DE'
#'NAVARRA, COMUNIDAD FORAL DE', 'PAÍS VASCO', 'RIOJA, LA', 'Ceuta', 'Melilla'
e=poblacion_ccaa_provincias['Edad (hasta 100 y más)'].unique()
e

In [ ]:
#Juntamos por CCAA y provincias y sumamos lo demás
nan='Total'
poblacion1=poblacion_ccaa_provincias.dropna(subset=['Edad (hasta 100 y más)'], axis=0, inplace=False)
poblacion1.head(10)